// import './globals.css'

import Link from "next/link"
import Navbar from "./components/Navbar"

// const inter = Inter({ subsets: ['latin'] })

// const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Link href={"/notes"}>Go to Notes</Link> <br />
            <Link href={"/dashboard"}>Go to Dashboard</Link> <br />
            <Link href={`/notes/${3}`}>Go to Single Note </Link> <br /> <br /> <br />
        {children}
      </body>
    </html>
  )
}
